version: '3'

services:
  user-app:
    image: ${AWS_ID}.dkr.ecr.us-east-2.amazonaws.com/user-service
    ports:
      - 8080:8080
    environment:
      - SPRING_APPLICATION_JSON=${SPRING_APPLICATION_JSON}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    networks:
      - qqd-network